# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd5aab3b17f863cc0119bbb9e97a94f4486bf709f2a71557ac680e1c44aee17b3bf9afaaf851cbf8bce8ee634fb0534a997f70fb418418b066d60790ee144104

test:
  secret_key_base: 8b86fbe2ae994d1f4ad8f184e0e65ed3136c01ef8acb61cf6db12939ccbd57227c67620d581d2a6185634358f3f5025f7615da17bba76869850ff76260f50a8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
